frontend:
  replicaCount: 2

  image:
    repository: priyanshu066/talktime-frontend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

backend:
  replicaCount: 2

  image:
    repository: priyanshu066/talktime-backend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3000
  s3:
    bucket: 
redis:
  replicaCount: 1

  image:
    repository: redis
    tag: "7"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 6379
