frontend:
  replicaCount: 1

  image:
    repository: priyanshu066/talktime-frontend
    tag: 5f51c8a7af26c5e67db8cd00909ae0caf54210c2
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

backend:
  replicaCount: 1

  image:
    repository: priyanshu066/talktime-backend
    tag: 5f51c8a7af26c5e67db8cd00909ae0caf54210c2
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3000
  s3:
    bucket: 
redis:
  replicaCount: 1

  image:
    repository: redis
    tag: "7"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 6379
