frontend:
  replicaCount: 1

  image:
    repository: priyanshu066/talktime-frontend
    tag: d13d5f430bd3d4fe6586a2ea73bdbd4f6db4665c
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

backend:
  replicaCount: 1

  image:
    repository: priyanshu066/talktime-backend
    tag: d13d5f430bd3d4fe6586a2ea73bdbd4f6db4665c
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3000
  s3:
    bucket: 
redis:
  replicaCount: 1

  image:
    repository: redis
    tag: "7"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 6379
