apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "talktime.fullname" . }}-backend-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  MONGODB_DB: "talktime"
  S3_REGION: "ap-south-1"
  CLIENT_URL: "http://localhost:5173"
  JWT_EXPIRES_IN: "7d"
  UPLOAD_DIR: "uploads"