apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "talktime.fullname" . }}-frontend
  labels:
    app: {{ include "talktime.name" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "talktime.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "talktime.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP