apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "talktime.fullname" . }}-redis
  labels:
    app: {{ include "talktime.name" . }}-redis
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "talktime.name" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "talktime.name" . }}-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP